export const images = {
    failed: require("../../../assets/lottie/failed.json"),
    processing: require("../../../assets/lottie/processing.json"),
    success: require("../../../assets/lottie/success.json"),
    testTubeProcess: require("../../../assets/lottie/testtube-process.json"),
    blurImagePlaceholder: require("../../../assets/blur-image-placeholder.png"),
    icon: require("../../../assets/icon.png"),
    landing_bg_image: require("../../../assets/landing-bg-image.png"),
    app_icon_bare: require("../../../assets/app-icon-bare.png"),
    ai_logo_1: require("../../../assets/ai-logo-1.png"),
    source_icon: require("../../../assets/source-icon-l.png"),
    readon_icon: require("../../../assets/readon-icon.png"),
    friday_icon: require("../../../assets/friday-icon.png"),
    summary_icon: require("../../../assets/summary-icon.png"),
    el15_icon: require("../../../assets/eli5-icon-l.png"),
    share_icon: require("../../../assets/share-icon-l.png"),
    three_friends: require("../../../assets/three-friends.png"),
    webLoading: require("../../../assets/lottie/webLoading.json"),
    rocketLogo: require("../../../assets/rocketLogo/dappstore-d-logo.png"),
    backgrondGif: require("../../../assets/backgroundGif.gif"),
    backgroundGifSmall: require("../../../assets/backgroundGifSmall.gif"),

    greenAuraBackdrop: require("../../../assets/aura-backdrops/green_aura_backdrop.png"),
    orangeAuraBackdrop: require("../../../assets/aura-backdrops/orange_aura_backdrop.png"),
    pinkAuraBackdrop: require("../../../assets/aura-backdrops/pink_aura_backdrop.png"),

    pointsFeatureIcon: require("../../../assets/feature-icons/points-feature-icon.png"),
    inviteFeatureIcon: require("../../../assets/feature-icons/invite-feature-icon.png"),
    updateFeatureIcon: require("../../../assets/feature-icons/update-feature-icon.png"),

    backgroundGradient1: require("../../../assets/lottie/background-gradient-animation-1.json"),
    googleIcon: require("../../../assets/googleIcon.png"),
    chatBoldIcon: require("../../../assets/chat-bold-icon.png"),
    chatOutlineIcon: require("../../../assets/chat-outline-icon.png"),
    feedBoldIcon: require("../../../assets/feed-bold-icon.png"),
    feedOutlineIcon: require("../../../assets/feed-outline-icon.png"),
    browserBoldIcon: require("../../../assets/browser-bold-icon.png"),
    browserOutlineIcon: require("../../../assets/browser-outline-icon.png"),
    vaultConnected: require("../../../assets/connected/connected.png"),
    vaultNotConnected: require("../../../assets/notConnected/notConnected.png"),
    postShareIcon: require("../../../assets/post-share-icon.png"),
    backgroundImage: require("../../../assets/background/background.png"),
    helpNextIcon: require("../../../assets/nextIcon/nextIcon.png"),
    chatIcon: require("../../../assets/chat/chat.png"),
    inviteMessageIcon: require("../../../assets/inviteMessageIcon/inviteMessageIcon.png"),
    profileHeaderMaleIcon : require("../../../assets/profileHeaderMaleIcon/profileHeaderMaleIcon.png"),
};
